# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FB_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geography', models.CharField(max_length=63)),
                ('issue_area', models.CharField(max_length=63)),
                ('subissue', models.CharField(max_length=63)),
                ('post_type', models.CharField(max_length=63)),
                ('post_date', models.DateTimeField()),
                ('alert_id', models.IntegerField()),
                ('link_to_post', models.CharField(max_length=127)),
                ('post_num_of_day', models.IntegerField()),
                ('subsource', models.CharField(max_length=31)),
                ('fb_link', models.CharField(max_length=63)),
                ('fb_shortlink', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=31)),
                ('option_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Subissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=31)),
                ('option_code', models.CharField(max_length=3)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.Issue')),
            ],
        ),
    ]
